version: '3'

services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 183passwordmanager
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    ports:
      - '8090:80'
    environment:
      PMA_HOST: database
